# Generated by Django 2.2.5 on 2019-10-28 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('duracao', models.DurationField()),
                ('ano', models.IntegerField()),
                ('num_musicas', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Musicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compositor', models.CharField(max_length=70)),
                ('artista', models.CharField(max_length=70)),
                ('titulo', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=20)),
                ('duracao', models.DurationField()),
                ('ano', models.IntegerField()),
                ('participacao', models.CharField(blank=True, max_length=70)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicas.Albuns')),
            ],
        ),
    ]
