# Generated by Django 2.2.5 on 2019-10-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albuns',
            options={'verbose_name_plural': 'Albuns'},
        ),
        migrations.AlterModelOptions(
            name='musicas',
            options={'verbose_name_plural': 'Musicas'},
        ),
        migrations.AlterField(
            model_name='musicas',
            name='participacao',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
