# Generated by Django 2.2.5 on 2019-12-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0003_auto_20191229_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14, verbose_name='Cpf'),
        ),
    ]
