# Generated by Django 2.2.5 on 2019-12-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0004_clientes_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='sobrenome',
            field=models.CharField(default='', max_length=70, verbose_name='Sobrenome'),
        ),
    ]
