# Generated by Django 2.2.5 on 2019-12-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0006_auto_20191230_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='password',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='username',
        ),
        migrations.AddField(
            model_name='clientes',
            name='login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicas.Logins'),
        ),
        migrations.AlterField(
            model_name='logins',
            name='password',
            field=models.CharField(default='password', max_length=40, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='logins',
            name='username',
            field=models.CharField(default='username', max_length=40, verbose_name='Usuário'),
        ),
    ]
