# Generated by Django 2.2.5 on 2019-12-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0008_auto_20191230_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='logins',
            name='some',
            field=models.CharField(max_length=40, null=True, verbose_name='Descrição'),
        ),
    ]
