# Generated by Django 2.2.5 on 2019-12-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0009_logins_some'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendas',
        ),
    ]
