# Generated by Django 2.2.5 on 2019-12-31 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0010_delete_vendas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicas.Albuns')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicas.Clientes')),
            ],
            options={
                'verbose_name_plural': 'Vendas',
            },
        ),
    ]
