# Generated by Django 2.2.5 on 2019-12-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0011_vendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
